classDiagram
class ZM_C1NP_{group: ZM_C1NP_
description: group node}
class ZM_C1NP_ansible_{group: ZM_C1NP_ansible_
description: group node}
ZM_C1NP_ --> ZM_C1NP_ansible_
class ZM_C1NP_ansible_inventories_{group: ZM_C1NP_ansible_inventories_
description: group node}
ZM_C1NP_ansible_ --> ZM_C1NP_ansible_inventories_
class ZM_C1NP_ansible_inventories_zm_c1np_{group: ZM_C1NP_ansible_inventories_zm_c1np_
description: group node}
ZM_C1NP_ansible_inventories_ --> ZM_C1NP_ansible_inventories_zm_c1np_
class ZM_C1NP_ansible_inventories_zm_c1np_technical_{group: ZM_C1NP_ansible_inventories_zm_c1np_technical_
description: group node}
ZM_C1NP_ansible_inventories_zm_c1np_ --> ZM_C1NP_ansible_inventories_zm_c1np_technical_
class ZM_C1NP_ansible_inventories_zm_c1np_technical_gestion_zone_service_zee_{project: gestion_zone_service_zee
description: None}
ZM_C1NP_ansible_inventories_zm_c1np_technical_ --> ZM_C1NP_ansible_inventories_zm_c1np_technical_gestion_zone_service_zee_
class ZM_C1NP_ansible_inventories_zm_c1np_technical_gestion_exposition_tech_{project: gestion_exposition_tech
description: None}
ZM_C1NP_ansible_inventories_zm_c1np_technical_ --> ZM_C1NP_ansible_inventories_zm_c1np_technical_gestion_exposition_tech_
class ZM_C1NP_ansible_inventories_zm_c1np_technical_wsus_zm_tech_{project: wsus_zm_tech
description: None}
ZM_C1NP_ansible_inventories_zm_c1np_technical_ --> ZM_C1NP_ansible_inventories_zm_c1np_technical_wsus_zm_tech_
class ZM_C1NP_ansible_inventories_zm_c1np_technical_gestion_zones_{project: gestion_zones
description: None}
ZM_C1NP_ansible_inventories_zm_c1np_technical_ --> ZM_C1NP_ansible_inventories_zm_c1np_technical_gestion_zones_
class ZM_C1NP_ansible_inventories_zm_c1np_functional_{group: ZM_C1NP_ansible_inventories_zm_c1np_functional_
description: group node}
ZM_C1NP_ansible_inventories_zm_c1np_ --> ZM_C1NP_ansible_inventories_zm_c1np_functional_
class ZM_C1NP_ansible_inventories_zm_c1np_functional_wsus_zm_fct_{project: wsus_zm_fct
description: None}
ZM_C1NP_ansible_inventories_zm_c1np_functional_ --> ZM_C1NP_ansible_inventories_zm_c1np_functional_wsus_zm_fct_
class ZM_C1NP_ansible_inventories_zm_c1np_functional_gestion_zone_service_{project: gestion_zone_service
description: None}
ZM_C1NP_ansible_inventories_zm_c1np_functional_ --> ZM_C1NP_ansible_inventories_zm_c1np_functional_gestion_zone_service_
class ZM_C1NP_ansible_inventories_zm_c1np_functional_gestion_zone_projet_{project: gestion_zone_projet
description: None}
ZM_C1NP_ansible_inventories_zm_c1np_functional_ --> ZM_C1NP_ansible_inventories_zm_c1np_functional_gestion_zone_projet_
class ZM_C1NP_ansible_inventories_c1np_css_{group: ZM_C1NP_ansible_inventories_c1np_css_
description: group node}
ZM_C1NP_ansible_inventories_ --> ZM_C1NP_ansible_inventories_c1np_css_
class ZM_C1NP_ansible_inventories_c1np_css_technical_{group: ZM_C1NP_ansible_inventories_c1np_css_technical_
description: group node}
ZM_C1NP_ansible_inventories_c1np_css_ --> ZM_C1NP_ansible_inventories_c1np_css_technical_
class ZM_C1NP_ansible_inventories_c1np_css_technical_wsus_css_tech_{project: wsus_css_tech
description: None}
ZM_C1NP_ansible_inventories_c1np_css_technical_ --> ZM_C1NP_ansible_inventories_c1np_css_technical_wsus_css_tech_
class ZM_C1NP_ansible_inventories_c1np_css_technical_rhsso_css_tech_{project: rhsso_css_tech
description: None}
ZM_C1NP_ansible_inventories_c1np_css_technical_ --> ZM_C1NP_ansible_inventories_c1np_css_technical_rhsso_css_tech_
class ZM_C1NP_ansible_inventories_c1np_css_technical_gitlab_css_tech_{project: gitlab_css_tech
description: None}
ZM_C1NP_ansible_inventories_c1np_css_technical_ --> ZM_C1NP_ansible_inventories_c1np_css_technical_gitlab_css_tech_
class ZM_C1NP_ansible_inventories_c1np_css_technical_commandements_css_tech_{project: commandements_css_tech
description: None}
ZM_C1NP_ansible_inventories_c1np_css_technical_ --> ZM_C1NP_ansible_inventories_c1np_css_technical_commandements_css_tech_
class ZM_C1NP_ansible_inventories_c1np_css_technical_artifactory_css_tech_{project: artifactory_css_tech
description: None}
ZM_C1NP_ansible_inventories_c1np_css_technical_ --> ZM_C1NP_ansible_inventories_c1np_css_technical_artifactory_css_tech_
class ZM_C1NP_ansible_inventories_c1np_css_technical_aap_css_tech_{project: aap_css_tech
description: None}
ZM_C1NP_ansible_inventories_c1np_css_technical_ --> ZM_C1NP_ansible_inventories_c1np_css_technical_aap_css_tech_
class ZM_C1NP_ansible_inventories_c1np_css_functional_{group: ZM_C1NP_ansible_inventories_c1np_css_functional_
description: group node}
ZM_C1NP_ansible_inventories_c1np_css_ --> ZM_C1NP_ansible_inventories_c1np_css_functional_
class ZM_C1NP_ansible_inventories_c1np_css_functional_wsus_css_fct_{project: wsus_css_fct
description: None}
ZM_C1NP_ansible_inventories_c1np_css_functional_ --> ZM_C1NP_ansible_inventories_c1np_css_functional_wsus_css_fct_
class ZM_C1NP_ansible_inventories_c1np_css_functional_rhsso_css_fct_{project: rhsso_css_fct
description: None}
ZM_C1NP_ansible_inventories_c1np_css_functional_ --> ZM_C1NP_ansible_inventories_c1np_css_functional_rhsso_css_fct_
class ZM_C1NP_ansible_inventories_c1np_css_functional_gitlab_css_fct_{project: gitlab_css_fct
description: None}
ZM_C1NP_ansible_inventories_c1np_css_functional_ --> ZM_C1NP_ansible_inventories_c1np_css_functional_gitlab_css_fct_
class ZM_C1NP_ansible_inventories_c1np_css_functional_commandements_css_fct_{project: commandements_css_fct
description: None}
ZM_C1NP_ansible_inventories_c1np_css_functional_ --> ZM_C1NP_ansible_inventories_c1np_css_functional_commandements_css_fct_
class ZM_C1NP_ansible_inventories_c1np_css_functional_artifactory_css_fct_{project: artifactory_css_fct
description: None}
ZM_C1NP_ansible_inventories_c1np_css_functional_ --> ZM_C1NP_ansible_inventories_c1np_css_functional_artifactory_css_fct_
class ZM_C1NP_ansible_inventories_c1np_css_functional_aap_css_fct_{project: aap_css_fct
description: None}
ZM_C1NP_ansible_inventories_c1np_css_functional_ --> ZM_C1NP_ansible_inventories_c1np_css_functional_aap_css_fct_
class ZM_C1NP_ansible_playbooks_{group: ZM_C1NP_ansible_playbooks_
description: group node}
ZM_C1NP_ansible_ --> ZM_C1NP_ansible_playbooks_
class ZM_C1NP_ansible_playbooks_Gestion_exposition_drive_{project: Gestion_exposition_drive
description: None}
ZM_C1NP_ansible_playbooks_ --> ZM_C1NP_ansible_playbooks_Gestion_exposition_drive_
class ZM_C1NP_ansible_playbooks_deploy_wsus_{project: deploy_wsus
description: None}
ZM_C1NP_ansible_playbooks_ --> ZM_C1NP_ansible_playbooks_deploy_wsus_
class ZM_C1NP_ansible_playbooks_remediation_{project: remediation
description: None}
ZM_C1NP_ansible_playbooks_ --> ZM_C1NP_ansible_playbooks_remediation_
class ZM_C1NP_ansible_playbooks_desenrolement_{project: desenrolement
description: None}
ZM_C1NP_ansible_playbooks_ --> ZM_C1NP_ansible_playbooks_desenrolement_
class ZM_C1NP_ansible_playbooks_gestion_zone_tenant_{project: gestion_zone_tenant
description: None}
ZM_C1NP_ansible_playbooks_ --> ZM_C1NP_ansible_playbooks_gestion_zone_tenant_
class ZM_C1NP_ansible_playbooks_gestion_zone_test_auto_{project: gestion_zone_test_auto
description: None}
ZM_C1NP_ansible_playbooks_ --> ZM_C1NP_ansible_playbooks_gestion_zone_test_auto_
class ZM_C1NP_ansible_playbooks_gestion_zone_infra_{project: gestion_zone_infra
description: None}
ZM_C1NP_ansible_playbooks_ --> ZM_C1NP_ansible_playbooks_gestion_zone_infra_
class ZM_C1NP_ansible_roles_{group: ZM_C1NP_ansible_roles_
description: group node}
ZM_C1NP_ansible_ --> ZM_C1NP_ansible_roles_
class ZM_C1NP_ansible_roles_commandements_{group: ZM_C1NP_ansible_roles_commandements_
description: group node}
ZM_C1NP_ansible_roles_ --> ZM_C1NP_ansible_roles_commandements_
class ZM_C1NP_ansible_roles_commandements_service-aap_{project: service-aap
description: None}
ZM_C1NP_ansible_roles_commandements_ --> ZM_C1NP_ansible_roles_commandements_service-aap_
class ZM_C1NP_ansible_roles_role-terraform-drive_{project: role-terraform-drive
description: Rôle de pilotage de terraform}
ZM_C1NP_ansible_roles_ --> ZM_C1NP_ansible_roles_role-terraform-drive_
class ZM_C1NP_ansible_roles_role-ldaps-drive-ad_{project: role-ldaps-drive-ad
description: Rôle de création des objets de l'AD en utilisant ansible pour piloter LDAPS}
ZM_C1NP_ansible_roles_ --> ZM_C1NP_ansible_roles_role-ldaps-drive-ad_
class ZM_C1NP_cloudmaker_{group: ZM_C1NP_cloudmaker_
description: group node}
ZM_C1NP_ --> ZM_C1NP_cloudmaker_
class ZM_C1NP_cloudmaker_gestion_exposition_{group: ZM_C1NP_cloudmaker_gestion_exposition_
description: group node}
ZM_C1NP_cloudmaker_ --> ZM_C1NP_cloudmaker_gestion_exposition_
class ZM_C1NP_cloudmaker_gestion_exposition_Gestion_exposition-runtime_{project: Gestion_exposition-runtime
description: None}
ZM_C1NP_cloudmaker_gestion_exposition_ --> ZM_C1NP_cloudmaker_gestion_exposition_Gestion_exposition-runtime_
class ZM_C1NP_delivery_{group: ZM_C1NP_delivery_
description: group node}
ZM_C1NP_ --> ZM_C1NP_delivery_
class ZM_C1NP_delivery_gestion_exposition_{project: gestion_exposition
description: None}
ZM_C1NP_delivery_ --> ZM_C1NP_delivery_gestion_exposition_
class ZM_C1NP_delivery_service-livraison_{project: service-livraison
description: None}
ZM_C1NP_delivery_ --> ZM_C1NP_delivery_service-livraison_
class ZM_C1NP_delivery_commandements_{project: commandements
description: None}
ZM_C1NP_delivery_ --> ZM_C1NP_delivery_commandements_
class ZM_C1NP_delivery_gestion_zone_{project: gestion_zone
description: None}
ZM_C1NP_delivery_ --> ZM_C1NP_delivery_gestion_zone_
class ZM_C1NP_ruche_{group: ZM_C1NP_ruche_
description: group node}
ZM_C1NP_ --> ZM_C1NP_ruche_
class ZM_C1NP_ruche_synchronisationah_{project: synchronisationah
description: }
ZM_C1NP_ruche_ --> ZM_C1NP_ruche_synchronisationah_
class ZM_C1NP_service-de-livraison-import_{project: Service de livraison import
description: None}
ZM_C1NP_ --> ZM_C1NP_service-de-livraison-import_
class ZM_C1NP_tests_bout_en_bout_{project: tests_bout_en_bout
description: None}
ZM_C1NP_ --> ZM_C1NP_tests_bout_en_bout_
class ZM_C1NP_vra_{group: ZM_C1NP_vra_
description: group node}
ZM_C1NP_ --> ZM_C1NP_vra_
class ZM_C1NP_vra_workflows_{project: workflows
description: None}
ZM_C1NP_vra_ --> ZM_C1NP_vra_workflows_
class ZM_C1NP_vra_custom_form_{project: custom_form
description: None}
ZM_C1NP_vra_ --> ZM_C1NP_vra_custom_form_
class ZM_C1NP_vra_blueprints_{project: blueprints
description: }
ZM_C1NP_vra_ --> ZM_C1NP_vra_blueprints_
